#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   Generates a working .env.

   .env.example is reference material — 200 lines explaining every setting and
   why it exists. That is the right thing to read second and the wrong thing to
   start from: most of it has sensible defaults, and someone standing up a new
   instance needs about six lines, two of which are secrets they should not
   invent by hand.

   This writes those lines, generates the secrets, and says what is still needed.

     node scripts/setup.js                       interactive-ish, sane defaults
     node scripts/setup.js --station WXYZ \
       --url https://stream.example.org:8000/live
   ═══════════════════════════════════════════════════════════════════════════ */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
// auth.js warns at load when SESSION_SECRET is unset. That is right for a
// running server and noise here, so give it one it will never use.
process.env.SESSION_SECRET = process.env.SESSION_SECRET || 'setup-script-placeholder';
const { hashPassword } = require('../auth');

const args = process.argv.slice(2);
const arg = (name, fallback) => {
  const i = args.indexOf('--' + name);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
};

const OUT = path.join(__dirname, '..', arg('out', '.env'));
if (fs.existsSync(OUT) && !args.includes('--force')) {
  console.error(`\n${OUT} already exists. Pass --force to overwrite it.\n`);
  process.exit(1);
}

const station = arg('station', 'MYSTATION');
const url = arg('url', 'https://stream.example.org:8000/live');
const tz = arg('tz', Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC');
const user = arg('user', 'admin');

// A passphrase, not a password: memorable enough to type, long enough to matter.
const WORDS = ['harbor', 'copper', 'lantern', 'meadow', 'falcon', 'pebble', 'thunder',
  'willow', 'cinder', 'marble', 'anchor', 'breeze', 'ember', 'forest', 'granite', 'ivory'];
const pick = () => WORDS[crypto.randomInt(WORDS.length)];
const password = `${pick()}-${pick()}-${crypto.randomInt(1000, 9999)}`;

let host = 'stream.example.org:8000';
let statusUrl = 'https://stream.example.org:8000/status-json.xsl';
try {
  const u = new URL(url);
  host = u.host;
  statusUrl = `${u.protocol}//${u.host}/status-json.xsl`;
} catch { /* keep the placeholders */ }

const slug = station.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'station';

const env = `# Generated by scripts/setup.js on ${new Date().toISOString().slice(0, 10)}
# Every other setting has a working default. See .env.example for all of them.

# ── What to monitor ─────────────────────────────────────────────────────────
# Seeds the configuration on FIRST BOOT only. After that the admin panel owns it
# and changes here are ignored — set CONFIG_RESEED=true to overwrite.
STREAMS=[{"id":"${slug}","name":"${station}","url":"${url}"}]
ICECAST_STATUS_URL=${statusUrl}
STATION_ID=${slug}
STATION_NAME=${station}
STATION_LABEL=${station}
STATION_TZ=${tz}

# ── Where the record lives ──────────────────────────────────────────────────
# MUST be a persistent volume. Without one every redeploy starts the incident
# record over, and uptime computed from an empty record looks perfect.
DATA_DIR=/app/data
PORT=3000

# ── Admin login ─────────────────────────────────────────────────────────────
# Password for ${user}: ${password}
#   ↑ WRITE THIS DOWN. It is not stored anywhere but the hash below.
ADMIN_USER=${user}
ADMIN_PASSWORD_HASH=${hashPassword(password)}
SESSION_SECRET=${crypto.randomBytes(32).toString('hex')}

# ── Email (optional — everything else works without it) ─────────────────────
# Prefer a send-only key from a transactional provider over a mailbox password:
# a mailbox password usually grants READ access to that mailbox too.
#   Postmark  smtp.postmarkapp.com : 587
#   Resend    smtp.resend.com      : 587
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM="${station} Stream Monitor <monitor@example.org>"
ALERT_EMAILS=

# Which stations may send email. Empty = all of them.
ALERT_STATIONS=
`;

fs.writeFileSync(OUT, env);

console.log(`
  Wrote ${OUT}

  ┌─────────────────────────────────────────────────────────┐
    Sign in with   ${user} / ${password}
    Write that down — only its hash is stored.
  └─────────────────────────────────────────────────────────┘

  Ready to run:      docker compose up -d
  Then open:         http://localhost:3000

  Still to fill in (optional — the app runs without them):
    SMTP_HOST / SMTP_USER / SMTP_PASS   to enable email alerts
    ALERT_EMAILS                        who receives them

  Everything else has a default. See .env.example for the full list.
`);
